import {
  mkdtemp,
  mkdir,
  readFile,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { afterEach, describe, expect, it, vi } from "vitest";
import { installAdapter as installCliAdapter } from "../packages/cli/install.js";
import {
  installOpencode,
  OPENCODE_MISSING_CLI_WARNING,
  OPENCODE_PLUGIN_MARKER,
  OPENCODE_PLUGIN_SOURCE,
} from "../packages/cli/install-opencode.js";

const roots: string[] = [];
const originalPath = process.env.PATH;
const originalWindowsPath = process.env.Path;

afterEach(async () => {
  vi.restoreAllMocks();
  if (originalPath === undefined) delete process.env.PATH;
  else process.env.PATH = originalPath;
  if (originalWindowsPath === undefined) delete process.env.Path;
  else process.env.Path = originalWindowsPath;
  await Promise.all(
    roots.splice(0).map((root) => rm(root, { recursive: true, force: true })),
  );
});

async function root(): Promise<string> {
  const value = await mkdtemp(join(tmpdir(), "subconscious-opencode-install-"));
  roots.push(value);
  return value;
}

describe("opencode installation", () => {
  it("installs the exact generated plugin only inside the target project", async () => {
    const project = await root();
    const unrelated = join(project, "keep.txt");
    const globalRoot = await root();
    const globalPlugin = join(
      globalRoot,
      ".opencode",
      "plugins",
      "subconscious.js",
    );
    await writeFile(unrelated, "keep me\n");
    await mkdir(join(globalRoot, ".opencode", "plugins"), { recursive: true });
    await writeFile(globalPlugin, "global copy\n");

    const result = await installOpencode(project);
    expect(result).toEqual({
      path: join(project, ".opencode", "plugins", "subconscious.js"),
      installed: true,
    });
    expect(await readFile(result.path, "utf8")).toBe(OPENCODE_PLUGIN_SOURCE);
    expect(await readFile(unrelated, "utf8")).toBe("keep me\n");
    expect(await readFile(globalPlugin, "utf8")).toBe("global copy\n");
  });

  it("is idempotent when the generated bytes are already current", async () => {
    const project = await root();
    const first = await installOpencode(project);
    const second = await installOpencode(project);

    expect(first.installed).toBe(true);
    expect(second).toEqual({ path: first.path, installed: false });
    expect(await readFile(first.path, "utf8")).toBe(OPENCODE_PLUGIN_SOURCE);
  });

  it("updates a generated-owned target back to the exact current source", async () => {
    const project = await root();
    const target = join(project, ".opencode", "plugins", "subconscious.js");
    await mkdir(join(project, ".opencode", "plugins"), { recursive: true });
    await writeFile(target, `${OPENCODE_PLUGIN_MARKER}\nold generated bytes\n`);

    const result = await installOpencode(project);
    expect(result.installed).toBe(true);
    expect(await readFile(target, "utf8")).toBe(OPENCODE_PLUGIN_SOURCE);
  });

  it("refuses to overwrite a conflicting target it does not own", async () => {
    const project = await root();
    const target = join(project, ".opencode", "plugins", "subconscious.js");
    await mkdir(join(project, ".opencode", "plugins"), { recursive: true });
    await writeFile(target, "custom plugin\n");

    await expect(installOpencode(project)).rejects.toThrow(
      /was not generated by Subconscious/,
    );
    expect(await readFile(target, "utf8")).toBe("custom plugin\n");
  });

  it("refuses a symlinked plugins directory and does not write outside the project", async () => {
    const project = await root();
    const outside = await root();
    const outsidePlugins = join(outside, "plugins");
    const outsideTarget = join(outsidePlugins, "subconscious.js");
    await mkdir(join(project, ".opencode"), { recursive: true });
    await mkdir(outsidePlugins, { recursive: true });
    await writeFile(outsideTarget, "outside copy\n");
    await symlink(outsidePlugins, join(project, ".opencode", "plugins"));

    await expect(installOpencode(project)).rejects.toThrow(
      /symlinked OpenCode plugin path/,
    );
    expect(await readFile(outsideTarget, "utf8")).toBe("outside copy\n");
  });

  it("keeps the public installer message in sync with the project-local install", async () => {
    const project = await root();

    const first = await installCliAdapter("opencode", project);
    const second = await installCliAdapter("opencode", project);

    expect(first).toContain("Installed the Subconscious plugin");
    expect(first).toContain("OpenCode picks it up on its next start.");
    expect(second).toContain("already installed");
  });

  it("ships a Windows .cmd launcher contract through ComSpec while keeping Unix direct spawn", () => {
    expect(OPENCODE_PLUGIN_SOURCE).toContain("var DELIVERY_TIMEOUT_MS = 4500;");
    expect(OPENCODE_PLUGIN_SOURCE).toContain(
      "command.toLowerCase().endsWith('.cmd')",
    );
    expect(OPENCODE_PLUGIN_SOURCE).toContain(
      "process.env.ComSpec || 'cmd.exe'",
    );
    expect(OPENCODE_PLUGIN_SOURCE).toContain(
      'spawn(command, ["opencode-bridge"]',
    );
  });

  it("warns once when subconscious is missing from PATH, then stays idle", async () => {
    const project = await root();
    const result = await installOpencode(project);
    expect(OPENCODE_PLUGIN_SOURCE).toContain(OPENCODE_MISSING_CLI_WARNING);

    const secretDir = join(project, "secret-bin-token");
    await mkdir(secretDir, { recursive: true });
    process.env.PATH = secretDir;
    process.env.Path = secretDir;

    const warnings: string[] = [];
    const warn = vi.spyOn(console, "warn").mockImplementation((...args) => {
      warnings.push(args.map(String).join(" "));
    });

    const module = await import(
      `${pathToFileURL(result.path).href}?missing-path=${Date.now()}`
    );
    const hooks = (await module.default({
      client: {
        session: {
          messages: async () => ({ data: [] }),
        },
      },
      directory: project,
    })) as {
      event?: (input: unknown) => Promise<void>;
      "chat.message"?: (
        messageInput: unknown,
        output: { parts: unknown[] },
      ) => Promise<void>;
      "experimental.chat.system.transform"?: (
        transformInput: unknown,
        output: { system: unknown[] },
      ) => Promise<void>;
      dispose?: () => Promise<void>;
    };

    const output = {
      parts: [{ type: "text", text: "hello", synthetic: false }],
    };
    const system = { system: ["existing"] };
    await hooks.event?.({
      event: {
        type: "session.created",
        properties: { info: { id: "session-1", directory: project } },
      },
    });
    await hooks["chat.message"]?.(
      { sessionID: "session-1", messageID: "msg-1" },
      output,
    );
    await hooks["experimental.chat.system.transform"]?.(
      { sessionID: "session-1" },
      system,
    );
    await hooks.event?.({
      event: {
        type: "session.status",
        properties: {
          sessionID: "session-1",
          status: { type: "idle" },
        },
      },
    });
    await hooks.dispose?.();

    expect(warnings).toEqual([OPENCODE_MISSING_CLI_WARNING]);
    expect(warnings.join("\n")).not.toContain(secretDir);
    expect(OPENCODE_PLUGIN_SOURCE).toContain(
      "if (bin) {\n    bridge = new Bridge(bin);\n  } else {",
    );
    expect(output.parts).toHaveLength(1);
    expect(system.system).toEqual(["existing"]);
    expect(warn).toHaveBeenCalledTimes(1);
  });
});
