import {
  mkdtemp,
  mkdir,
  readFile,
  rm,
  symlink,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { installAdapter as installCliAdapter } from "../packages/cli/install.js";
import {
  installOpencode,
  OPENCODE_PLUGIN_MARKER,
  OPENCODE_PLUGIN_SOURCE,
} from "../packages/cli/install-opencode.js";

const roots: string[] = [];

afterEach(async () => {
  await Promise.all(
    roots.splice(0).map((root) => rm(root, { recursive: true, force: true })),
  );
});

async function root(): Promise<string> {
  const value = await mkdtemp(join(tmpdir(), "subconscious-opencode-install-"));
  roots.push(value);
  return value;
}

describe("opencode installation", () => {
  it("installs the exact generated plugin only inside the target project", async () => {
    const project = await root();
    const unrelated = join(project, "keep.txt");
    const globalRoot = await root();
    const globalPlugin = join(
      globalRoot,
      ".opencode",
      "plugins",
      "subconscious.js",
    );
    await writeFile(unrelated, "keep me\n");
    await mkdir(join(globalRoot, ".opencode", "plugins"), { recursive: true });
    await writeFile(globalPlugin, "global copy\n");

    const result = await installOpencode(project);
    expect(result).toEqual({
      path: join(project, ".opencode", "plugins", "subconscious.js"),
      installed: true,
    });
    expect(await readFile(result.path, "utf8")).toBe(OPENCODE_PLUGIN_SOURCE);
    expect(await readFile(unrelated, "utf8")).toBe("keep me\n");
    expect(await readFile(globalPlugin, "utf8")).toBe("global copy\n");
  });

  it("is idempotent when the generated bytes are already current", async () => {
    const project = await root();
    const first = await installOpencode(project);
    const second = await installOpencode(project);

    expect(first.installed).toBe(true);
    expect(second).toEqual({ path: first.path, installed: false });
    expect(await readFile(first.path, "utf8")).toBe(OPENCODE_PLUGIN_SOURCE);
  });

  it("updates a generated-owned target back to the exact current source", async () => {
    const project = await root();
    const target = join(project, ".opencode", "plugins", "subconscious.js");
    await mkdir(join(project, ".opencode", "plugins"), { recursive: true });
    await writeFile(target, `${OPENCODE_PLUGIN_MARKER}\nold generated bytes\n`);

    const result = await installOpencode(project);
    expect(result.installed).toBe(true);
    expect(await readFile(target, "utf8")).toBe(OPENCODE_PLUGIN_SOURCE);
  });

  it("refuses to overwrite a conflicting target it does not own", async () => {
    const project = await root();
    const target = join(project, ".opencode", "plugins", "subconscious.js");
    await mkdir(join(project, ".opencode", "plugins"), { recursive: true });
    await writeFile(target, "custom plugin\n");

    await expect(installOpencode(project)).rejects.toThrow(
      /was not generated by Subconscious/,
    );
    expect(await readFile(target, "utf8")).toBe("custom plugin\n");
  });

  it("refuses a symlinked plugins directory and does not write outside the project", async () => {
    const project = await root();
    const outside = await root();
    const outsidePlugins = join(outside, "plugins");
    const outsideTarget = join(outsidePlugins, "subconscious.js");
    await mkdir(join(project, ".opencode"), { recursive: true });
    await mkdir(outsidePlugins, { recursive: true });
    await writeFile(outsideTarget, "outside copy\n");
    await symlink(outsidePlugins, join(project, ".opencode", "plugins"));

    await expect(installOpencode(project)).rejects.toThrow(
      /symlinked OpenCode plugin path/,
    );
    expect(await readFile(outsideTarget, "utf8")).toBe("outside copy\n");
  });

  it("keeps the public installer message in sync with the project-local install", async () => {
    const project = await root();

    const first = await installCliAdapter("opencode", project);
    const second = await installCliAdapter("opencode", project);

    expect(first).toContain("Installed the Subconscious plugin");
    expect(first).toContain("OpenCode picks it up on its next start.");
    expect(second).toContain("already installed");
  });

  it("ships a Windows .cmd launcher contract through ComSpec while keeping Unix direct spawn", () => {
    expect(OPENCODE_PLUGIN_SOURCE).toContain("var DELIVERY_TIMEOUT_MS = 4500;");
    expect(OPENCODE_PLUGIN_SOURCE).toContain(
      "command.toLowerCase().endsWith('.cmd')",
    );
    expect(OPENCODE_PLUGIN_SOURCE).toContain(
      "process.env.ComSpec || 'cmd.exe'",
    );
    expect(OPENCODE_PLUGIN_SOURCE).toContain(
      'spawn(command, ["opencode-bridge"]',
    );
  });
});
